"""initial schema

Revision ID: f72b9bbcef2d
Revises:
Create Date: 2026-04-11 07:00:18.614408

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f72b9bbcef2d"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "languages",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "songs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("composer", sa.String(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "word_classes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("abbreviation", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "verses",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("song_id", sa.Integer(), nullable=False),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("content", sa.JSON(), nullable=False),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["song_id"],
            ["songs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "words",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("text", sa.String(), nullable=False),
        sa.Column("pronunciation", sa.String(), nullable=True),
        sa.Column("definition", sa.String(), nullable=True),
        sa.Column("example_original", sa.String(), nullable=True),
        sa.Column("example_translation", sa.String(), nullable=True),
        sa.Column("word_class_id", sa.Integer(), nullable=True),
        sa.Column("language_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["language_id"],
            ["languages.id"],
        ),
        sa.ForeignKeyConstraint(
            ["word_class_id"],
            ["word_classes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("words", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_words_text"), ["text"], unique=False)

    op.create_table(
        "meanings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("word_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["word_id"],
            ["words.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "word_related",
        sa.Column("word_id", sa.Integer(), nullable=False),
        sa.Column("related_word_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["related_word_id"],
            ["words.id"],
        ),
        sa.ForeignKeyConstraint(
            ["word_id"],
            ["words.id"],
        ),
        sa.PrimaryKeyConstraint("word_id", "related_word_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("word_related")
    op.drop_table("meanings")
    with op.batch_alter_table("words", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_words_text"))

    op.drop_table("words")
    op.drop_table("verses")
    op.drop_table("word_classes")
    op.drop_table("songs")
    op.drop_table("languages")
    # ### end Alembic commands ###
