name: Kamus Bahasa Moy - CD (Deployment)

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    environment: production
    # only deploy when a release is published
    if: github.event_name == 'release' || github.event_name == 'workflow_dispatch'

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy
        uses: appleboy/ssh-action@v1.2.5
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /var/www/kamusbahasamoy

            if [ "${{ github.event_name }}" = "release" ]; then
              TARGET="${{ github.event.release.tag_name }}"
            else
              TARGET="main"
            fi


            echo "🚀 Deploying target: $TARGET"
            git fetch --all --tags
            git checkout $TARGET
            git pull origin $TARGET || echo "Skipping pull if tag"

            # Restart services
            docker compose down
            docker compose up -d --build

            # Run initialization
            docker exec kamus-api uv run alembic upgrade head
            docker exec kamus-api uv run python scripts/seed.py

  notify-discord:
    name: Notify Discord
    runs-on: ubuntu-latest
    needs: [deploy]
    if: always()
    steps:
      - name: Success Notification
        if: needs.deploy.result == 'success'
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          title: "✅ [Kamus Bahasa Moy] Deployment Successful!"
          description: |
            **Event:** `${{ github.event_name }}`
            **Target:** `${{ github.event.release.tag_name || 'main' }}`
            **Commit:** `${{ github.event.release.target_commitish || github.sha }}`
            **Actor:** @${{ github.actor }}

            🚀 Production is now up to date!
          color: 0x00ff00

      - name: Failure Notification
        if: needs.deploy.result == 'failure'
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          title: "❌ [Kamus Bahasa Moy] Deployment Failed!"
          description: |
            **Event:** `${{ github.event_name }}`
            **Actor:** @${{ github.actor }}

            🔗 Logs:
            ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          color: 0xff0000
